// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC082soW16OwD0y8h1UStrNXSXCLcre3x4',
    appId: '1:387778797712:web:35b6faf1e35a551d26f815',
    messagingSenderId: '387778797712',
    projectId: 'flutter-web-a67cd',
    authDomain: 'flutter-web-a67cd.firebaseapp.com',
    storageBucket: 'flutter-web-a67cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwXZV1E5nQZmHOhuWIDKUneXJoP2U2Yxk',
    appId: '1:387778797712:android:0bc5fc049c64b6be26f815',
    messagingSenderId: '387778797712',
    projectId: 'flutter-web-a67cd',
    storageBucket: 'flutter-web-a67cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyu1_Zq0PlA7hpNydEAuL09kGQ2Ff1cfo',
    appId: '1:387778797712:ios:4ff2acff465d2e7426f815',
    messagingSenderId: '387778797712',
    projectId: 'flutter-web-a67cd',
    storageBucket: 'flutter-web-a67cd.appspot.com',
    iosClientId: '387778797712-uue8mf84nfc789u4ol9tvqlg92rsd4rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeb',
  );
}
